# Generated by Django 3.2.9 on 2021-12-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0004_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='purchase',
        ),
    ]
