# Generated by Django 3.2.9 on 2021-12-06 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0006_alter_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='order',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferumbel.purchase'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='delivery',
            field=models.BooleanField(blank=True, null=True, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='name',
            field=models.CharField(max_length=200, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='value',
            field=models.TextField(blank=True, null=True, verbose_name='Значение'),
        ),
    ]
