# Generated by Django 3.2.9 on 2021-12-06 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0008_order_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefits',
            options={'ordering': ['id'], 'verbose_name': 'Benefict', 'verbose_name_plural': 'Benefits'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['id'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['id'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='photos',
            options={'ordering': ['id'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterModelOptions(
            name='sections',
            options={'ordering': ['id'], 'verbose_name': 'Selection', 'verbose_name_plural': 'Selections'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['id'], 'verbose_name': 'Текст', 'verbose_name_plural': 'Texts'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['id'], 'verbose_name': 'Timetable', 'verbose_name_plural': 'Timetables'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AlterField(
            model_name='benefits',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='value',
            field=models.TextField(verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Text',
            field=models.TextField(blank=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_main',
            field=models.BooleanField(default=True, verbose_name='Главная'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='adr',
            field=models.URLField(null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='pole',
            field=models.TextField(null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='value',
            field=models.CharField(max_length=40, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='Image',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferumbel.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='coast',
            field=models.TextField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='division',
            field=models.TextField(blank=True, null=True, verbose_name='Разделение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='popular',
            field=models.FloatField(default=0, verbose_name='Популярность'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='isMain',
            field=models.BooleanField(verbose_name='Главная'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferumbel.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='text',
            name='value',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
