# Generated by Django 3.2.9 on 2022-01-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0010_auto_20211230_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
