# Generated by Django 3.2.9 on 2022-01-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0012_alter_profile_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
