# Generated by Django 3.2.9 on 2022-01-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0013_order_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='index',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
