# Generated by Django 3.2.9 on 2022-01-26 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0014_purchase_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferumbel.purchase'),
        ),
    ]
