# Generated by Django 3.2.9 on 2022-01-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0015_alter_order_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coast',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
