# Generated by Django 3.2.9 on 2022-01-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0016_order_coast'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='statuc',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
