# Generated by Django 3.2.9 on 2022-01-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0020_alter_customer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Text',
        ),
        migrations.AddField(
            model_name='customer',
            name='ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
