# Generated by Django 3.2.9 on 2022-03-08 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0025_auto_20220207_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Порядок', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
