# Generated by Django 3.2.9 on 2022-03-08 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0026_auto_20220308_0135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
    ]
