# Generated by Django 3.2.9 on 2022-03-08 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0027_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Юзер', 'verbose_name_plural': 'Юзеры'},
        ),
    ]
