# Generated by Django 3.2.9 on 2022-03-09 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0028_auto_20220308_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing', models.BooleanField(blank=True, default=False, null=True)),
                ('service', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='division',
        ),
        migrations.AddField(
            model_name='product',
            name='separation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferumbel.division', verbose_name='Разделение'),
        ),
    ]
