# Generated by Django 3.2.9 on 2022-03-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0030_auto_20220309_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=1000, verbose_name='Название'),
        ),
    ]
