# Generated by Django 3.2.9 on 2022-03-18 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ferumbel', '0033_auto_20220317_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Продавец', 'verbose_name_plural': 'Продавцы'},
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='delivery',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='foruser',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Связь с пользователем'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Индекс продавца'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='adress',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='index',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferumbel.customer', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
