# Generated by Django 3.2.9 on 2022-03-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0034_auto_20220318_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Имя пользователя'),
        ),
    ]
