# Generated by Django 3.2.9 on 2022-04-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0035_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='html_field',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
