# Generated by Django 3.2.9 on 2022-04-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0036_product_html_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='html_field',
        ),
    ]
