# Generated by Django 3.2.9 on 2022-04-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0039_alter_product_coast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='purchase',
        ),
        migrations.AddField(
            model_name='order',
            name='purchase',
            field=models.ManyToManyField(blank=True, null=True, to='ferumbel.Purchase', verbose_name='Корзина'),
        ),
    ]
