# Generated by Django 3.2.9 on 2022-04-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0040_auto_20220415_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Text',
            field=models.TextField(blank=True, max_length=100, verbose_name='Название'),
        ),
    ]
