# Generated by Django 3.2.9 on 2022-04-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0042_alter_category_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
    ]
