# Generated by Django 3.2.9 on 2022-05-11 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0044_alter_category_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='purchase',
        ),
        migrations.AddField(
            model_name='order',
            name='purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferumbel.purchase', verbose_name='Корзина'),
        ),
    ]
