# Generated by Django 3.2.9 on 2022-07-27 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0046_category_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferumbel.product', verbose_name='Картинки'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='adr',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferumbel.purchase', verbose_name=' Корзина'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='coast',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
    ]
