# Generated by Django 3.2.9 on 2022-07-27 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0047_auto_20220727_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferumbel.product', verbose_name='Продукт'),
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole', models.TextField(blank=True, null=True, verbose_name='Поле')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Значение')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferumbel.product', verbose_name='Продукт')),
            ],
        ),
    ]
