# Generated by Django 3.2.9 on 2022-07-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0048_auto_20220727_0748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristic',
            options={'verbose_name': 'Characteristic', 'verbose_name_plural': 'Characteristics'},
        ),
    ]
