# Generated by Django 3.2.9 on 2022-07-27 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0049_alter_characteristic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristic',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferumbel.product', verbose_name='Продукт'),
        ),
    ]
