# Generated by Django 3.2.9 on 2022-08-09 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0050_auto_20220727_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferumbel.product', verbose_name='Продукт'),
        ),
    ]
