# Generated by Django 4.1 on 2022-09-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0053_remove_product_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristic',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='charact',
            field=models.ManyToManyField(to='ferumbel.characteristic', verbose_name='Характеристика'),
        ),
    ]
