# Generated by Django 4.1 on 2022-09-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0054_remove_characteristic_product_product_charact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='charact',
            field=models.ManyToManyField(blank=True, null=True, to='ferumbel.characteristic', verbose_name='Характеристика'),
        ),
    ]
