# Generated by Django 4.1 on 2022-09-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0056_remove_product_charact_product_charact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='charact',
        ),
        migrations.AddField(
            model_name='product',
            name='charact',
            field=models.ManyToManyField(blank=True, null=True, to='ferumbel.characteristic', verbose_name='Характеристика'),
        ),
    ]
