# Generated by Django 4.1 on 2022-10-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0057_remove_product_charact_product_charact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0, verbose_name='Коэффициент')),
            ],
            options={
                'verbose_name': 'Curs',
                'verbose_name_plural': 'Curses',
            },
        ),
    ]
